---
- name: This playbook copies to remote machines
  hosts: all
  become: true

  tasks:
  - name: copying a file
    copy: 
      src: /opt/ansible/index.html
      dest: /home/ansadmin
      mode: 0600
      owner: Adnan

       
